In [13]:
import ast
import pandas as pd

In [32]:
with open('results_logistic_l2_raw.txt', 'r') as f:
    results_lines = f.readlines()
    
results = []

for line in results_lines:
    results.append( ast.literal_eval(line) )
    
for result in results:
    result['features'] = ast.literal_eval(result['features'])
    result['params'] = ast.literal_eval(result['params'])
    
result_tuples = []
for result in results:
    result_tuples.append( (result['error'], result['params']['C'], result['params']['max_iter'] ) )

In [10]:
min(results, key=lambda x: x['error'])

{'classifier': 'Logistic Regression L2',
 'error': 0.13589251439539352,
 'features': ('age',
  'workclass',
  'education-num',
  'occupation',
  'relationship',
  'race',
  'sex',
  'capital-gain',
  'capital-loss',
  'hours-per-week',
  'native-country'),
 'params': {'C': 4.1, 'max_iter': 50, 'penalty': 'l2'}}

In [33]:
with open('results_logistic_l2.txt', 'w') as f:
    f.write('error, lambda, num_iter, features\n')
    
    for result in results:
        f.write('{}, {}, {}, {}\n'.format(result['error'], result['params']['C'], result['params']['max_iter'], result['features']))

In [14]:
df = pd.DataFrame(result_tuples, columns=['error', 'C', 'max_iter'])

In [28]:
df

        error    C  max_iter
0    0.157390  0.1        10
1    0.136660  0.1        50
2    0.136660  0.1       100
3    0.136660  0.1       200
4    0.159309  0.2        10
5    0.137428  0.2        50
6    0.137428  0.2       100
7    0.137428  0.2       200
8    0.159693  0.3        10
9    0.137812  0.3        50
10   0.137812  0.3       100
11   0.137812  0.3       200
12   0.158925  0.4        10
13   0.137044  0.4        50
14   0.137044  0.4       100
15   0.137044  0.4       200
16   0.157390  0.5        10
17   0.136660  0.5        50
18   0.136660  0.5       100
19   0.136660  0.5       200
20   0.158925  0.6        10
21   0.138196  0.6        50
22   0.138196  0.6       100
23   0.138196  0.6       200
24   0.159309  0.7        10
25   0.136660  0.7        50
26   0.136660  0.7       100
27   0.136660  0.7       200
28   0.158541  0.8        10
29   0.137044  0.8        50
..        ...  ...       ...
170  0.138196  4.3       100
171  0.138196  4.3       200
172  0.157006  4.4        10
173  0.136660  4.4        50
174  0.136660  4.4       100
175  0.136660  4.4       200
176  0.157006  4.5        10
177  0.136660  4.5        50
178  0.136660  4.5       100
179  0.136660  4.5       200
180  0.159309  4.6        10
181  0.137428  4.6        50
182  0.137428  4.6       100
183  0.137428  4.6       200
184  0.157006  4.7        10
185  0.138196  4.7        50
186  0.138196  4.7       100
187  0.138196  4.7       200
188  0.160077  4.8        10
189  0.136660  4.8        50
190  0.136660  4.8       100
191  0.136660  4.8       200
192  0.157006  4.9        10
193  0.137428  4.9        50
194  0.137428  4.9       100
195  0.137428  4.9       200
196  0.159309  5.0        10
197  0.137044  5.0        50
198  0.137044  5.0       100
199  0.137044  5.0       200

[200 rows x 3 columns]

In [22]:
df['max_iter'].unique()

array([ 10,  50, 100, 200])

In [27]:
df[ df['max_iter'] == 100 ]['error'].values

array([ 0.13666027,  0.13742802,  0.1378119 ,  0.13704415,  0.13666027,
        0.13819578,  0.13666027,  0.13704415,  0.13742802,  0.1378119 ,
        0.13666027,  0.1378119 ,  0.13666027,  0.13666027,  0.13666027,
        0.13666027,  0.13819578,  0.13704415,  0.13704415,  0.13742802,
        0.13704415,  0.13819578,  0.1378119 ,  0.1378119 ,  0.13704415,
        0.13742802,  0.13742802,  0.13819578,  0.13742802,  0.13819578,
        0.13666027,  0.13819578,  0.1378119 ,  0.13742802,  0.13666027,
        0.1378119 ,  0.13742802,  0.13666027,  0.13742802,  0.13857965,
        0.13589251,  0.13666027,  0.13819578,  0.13666027,  0.13666027,
        0.13742802,  0.13819578,  0.13666027,  0.13742802,  0.13704415])